apiVersion: v2
name: homer
description: A dead simple static HOMepage for your servER to keep your services on hand, from a simple yaml configuration file.
home: https://charts.gabe565.com/charts/homer
icon: https://raw.githubusercontent.com/bastienwirtz/homer/5609315fe77da5441a9c3dda8d92c0ffe9f1bf17/public/assets/icons/logo.svg
type: application
version: 0.4.3
# renovate datasource=docker depName=b4bz/homer
appVersion: v23.02.2
kubeVersion: ">=1.22.0-0"
keywords:
  - homer
  - dashboard
  - startpage
  - homepage
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
sources:
  - https://github.com/gabe565/charts/tree/main/charts/homer
  - https://github.com/bastienwirtz/homer
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Add default values for codeserver addon
    - kind: added
      description: Add example ingress values
