{{- with .Values.auth.borg }}
{{- $existingSec := (lookup "v1" "Secret" $.Release.Namespace (include "borgmatic.borgSecretName" $)).data }}
{{- if not .existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "borgmatic.borgSecretName" $ }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "borgmatic.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- if $existingSec }}
  repokey: {{ index $existingSec "repokey" }}
  {{- else }}
  repokey: {{ .length | int | randAlphaNum | b64enc }}
  {{- end }}
{{- end }}
{{- end }}