{{- with .Values.backup }}
{{- if not .existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "borgmatic.fullname" $ }}
data:
  {{- with .crontab }}
  crontab.txt: |
    {{ .pruneCreate }} PATH=$PATH:/usr/bin /usr/bin/borgmatic --stats -v0 prune create 2>&1
    {{ .check }} PATH=$PATH:/usr/bin /usr/bin/borgmatic -v0 check 2>&1
  {{- end }}

  {{- $prefix := tpl .prefix $ }}
  config.yaml: |
    location:
      repositories:
        {{- if .localRepo }}
        - /mnt/borg-repository
        {{- end }}

        {{- range .repos }}
        - {{ . }}
        {{- end }}

      {{- with .claims }}
      source_directories:
        {{- range . }}
        {{- if .mountPath }}
        - {{ .mountPath }}
        {{- else }}
        - /mnt/source/{{ .claimName }}
        {{- end }}
        {{- end }}
      {{- else }}
      source_directories: []
      {{- end }}
    storage:
      archive_name_format: "{{ $prefix }}-{now:%Y-%m-%d-%H%M%S}"
      ssh_command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=ERROR
    {{- with .keep }}
    retention:
      keep_hourly: {{ .hourly }}
      keep_daily: {{ .daily }}
      keep_monthly: {{ .monthly }}
      keep_yearly: {{ .yearly }}
      prefix: "{{ $prefix }}-"
    {{- end }}
    consistency:
      check_last: {{ .checkLast }}
      prefix: "{{ $prefix }}-"
    hooks:
      {{- with .healthchecks }}
      healthchecks: {{ . }}
      {{- end }}

      {{- with .postgresql }}
      {{- if .enabled }}
      postgresql_databases:
        - name: {{ .database }}
          username: {{ .username }}
          hostname: {{ .hostname }}
          format: {{ .format }}
          options: --no-owner
      {{- end }}
      {{- end }}

      {{- with .mariadb }}
      {{- if .enabled }}
      mysql_databases:
        - name: {{ .database }}
          username: {{ .username }}
          hostname: {{ .hostname }}
          options: --skip-comments
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
