{{- with .Values.persistence }}
{{- if not .existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "borgmatic.fullname" $ }}
  annotations:
    "helm.sh/resource-policy": "keep"
    {{- with .annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "borgmatic.labels" $ | nindent 4 }}
spec:
  {{- with .storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .size }}
  {{- with .selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .dataSource }}
  dataSource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
