{{- with .Values.auth.ssh }}
{{- if and .enabled (not .existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "borgmatic.sshSecretName" $ }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "borgmatic.labels" $ | nindent 4 }}
type: Opaque
data:
  id_{{ .type }}: {{ .key | b64enc }}
{{- end }}
{{- end }}