{{/* Append the hardcoded settings */}}
{{- define "vaultwarden.harcodedValues" -}}
env:
  {{- with .Values.ingress.main }}
  {{- if .enabled }}
  DOMAIN: http{{ if .tls }}s{{ end }}://{{ (first .hosts).host }}
  {{- end }}
  {{- end }}

  ROCKET_PORT: {{ quote .Values.service.main.ports.http.port }}

  {{- with .Values.service.main.ports.websocket }}
  WEBSOCKET_ENABLED: {{ quote .enabled }}
  WEBSOCKET_PORT: {{ quote .port }}
  {{- end }}

  {{- if .Values.postgresql.enabled }}
  {{- with .Values.postgresql }}
  DATABASE_PASSWORD:
    secretKeyRef:
      name: {{ $.Release.Name }}-postgresql
      key: {{ if not .auth.password }}postgres-{{ end }}password
  DATABASE_URL: postgresql://{{ default "postgres" .auth.username }}:$(DATABASE_PASSWORD)@{{ $.Release.Name }}-postgresql/{{ .auth.database }}
  {{- end }}
  {{- else if .Values.mariadb.enabled }}
  {{- with .Values.mariadb}}
  DATABASE_PASSWORD:
    secretKeyRef:
      name: {{ $.Release.Name }}-mariadb
      key: mariadb-password
  DATABASE_URL: mysql://{{ .auth.username }}:$(DATABASE_PASSWORD)@{{ $.Release.Name }}-mariadb/{{ .auth.database }}
  {{- end }}
  {{- end }}
{{- end -}}
{{- $_ := merge .Values (include "vaultwarden.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
