repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: remove-crlf
      - id: remove-tabs

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs

  - repo: local
    hooks:
      - id: gen-chart-summary
        name: Generate Chart Summary
        entry: hack/gen-chart-summary.sh
        language: system
        files: Chart\.yaml$
        pass_filenames: false
