apiVersion: v2
name: bookstack
description: A simple, self-hosted, easy-to-use platform for organising and storing information.
home: https://github.com/gabe565/charts/tree/main/charts/bookstack
icon: https://media.githubusercontent.com/media/BookStackApp/website/main/static/images/logo.png
type: application
version: 0.1.1
appVersion: 22.10.1
kubeVersion: ">=1.16.0-0"
keywords:
  - bookstack
  - wiki
  - documentation
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.0
  - name: mariadb
    version: 11.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
sources:
  - https://bookstackapp.com
  - https://github.com/BookStackApp/BookStack
  - https://ghcr.io/linuxserver/bookstack
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Bump appVersion to v22.10.1
