{{/* Append the hardcoded settings */}}
{{- define "memos.harcodedValues" -}}
env:
  MEMOS_PORT: {{ .Values.service.main.ports.http.port }}

  {{- with .Values.mariadb}}
  {{- if .enabled }}
  MEMOS_DRIVER: mysql
  DB_PASSWORD:
    secretKeyRef:
      name: {{ $.Release.Name }}-mariadb
      key: mariadb-password
  MEMOS_DSN: {{ .auth.username }}:$(DB_PASSWORD)@tcp({{ $.Release.Name }}-mariadb)/{{ .auth.database }}
  {{- end }}
  {{- end }}
{{- end -}}
{{- $_ := merge .Values (include "memos.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
