{{/* Append the hardcoded settings */}}
{{- define "memos.harcodedValues" -}}
env:
  MEMOS_PORT: {{ .Values.service.main.ports.http.port }}
{{- end -}}
{{- $_ := merge .Values (include "memos.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
