#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: diygod/rsshub
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 2022-07-29

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- environment variables.
# @default -- See below
env:
  NODE_ENV: production

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 1200

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Enable and configure redis subchart under this key.
#    For more options see [redis chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/redis)
# @default -- See values.yaml
redis:
  enabled: true
  replica:
    replicaCount: 0
