{{/* Append the hardcoded settings */}}
{{- define "pictshare.harcodedValues" -}}
env:
  {{- with .Values.ingress.main }}
  {{- if .enabled }}
  URL: http{{ if .tls }}s{{ end }}://{{ (first .hosts).host }}/
  {{- end -}}
  {{- end }}

termination:
  gracePeriodSeconds: "0"
{{- end -}}
{{- $_ := merge .Values (include "pictshare.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
