{{/* Append the hardcoded settings */}}
{{- define "headscale.harcodedValues" -}}
args: ["headscale", "serve"]

initContainers:
  config:
    image: alpine
    volumeMounts:
      {{- if .Values.persistence.config.enabled }}
      - name: config
        mountPath: /etc/headscale
      {{- end }}
    command:
      - sh
      - -c
      - |
        cat <<'EOF' >/etc/headscale/config.yaml
        # Please use environment variables to configure Headscale.
        # For config reference, see https://github.com/juanfont/headscale/blob/main/config-example.yaml
        # To configure any of these as an env:
        #   1. Flatten object keys using "_"
        #   2. Prefix with "HEADSCALE_"
        #
        # For example:
        #   - "listen_addr" becomes "HEADSCALE_LISTEN_ADDR"
        #   - "log.level" becomes "HEADSCALE_LOG_LEVEL"
        EOF

env:
  {{- with .Values.ingress.main }}
  {{- if .enabled }}
  HEADSCALE_SERVER_URL: http{{ if .tls }}s{{ end }}://{{ (first .hosts).host }}
  {{- end }}
  {{- end }}

  {{- with .Values.service.main.ports }}
  HEADSCALE_LISTEN_ADDR: "0.0.0.0:{{ .http.port }}"
  HEADSCALE_METRICS_LISTEN_ADDR: "0.0.0.0:{{ .metrics.port }}"
  {{- end }}

  HEADSCALE_PRIVATE_KEY_PATH: "/etc/headscale/private.key"
  HEADSCALE_NOISE: "{}"
  HEADSCALE_NOISE_PRIVATE_KEY_PATH: "/etc/headscale/noise_private.key"
  HEADSCALE_DB_PATH: "/etc/headscale/db.sqlite"

  {{- with .Values.postgresql }}
  {{- if .enabled }}
  HEADSCALE_DB_TYPE: postgres
  HEADSCALE_DB_HOST: {{ $.Release.Name }}-postgresql
  HEADSCALE_DB_PORT: "5432"
  HEADSCALE_DB_NAME: {{ .auth.database }}
  HEADSCALE_DB_USER: {{ default "postgres" .auth.username }}
  HEADSCALE_DB_PASS:
    secretKeyRef:
      name: {{ $.Release.Name }}-postgresql
      key: {{ if not .auth.password }}postgres-{{ end }}password
  {{- end }}
  {{- end }}
{{- end -}}
{{- $_ := merge .Values (include "headscale.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
