apiVersion: v2
name: tandoor
description: Application for managing recipes, planning meals, building shopping lists and much much more!
home: https://github.com/gabe565/charts/tree/main/charts/tandoor
icon: https://raw.githubusercontent.com/vabene1111/recipes/master/docs/logo_color.svg
version: 0.1.1
appVersion: 1.4.4
kubeVersion: ">=1.16.0-0"
keywords:
  - recipes
  - cookbook
  - cooking
  - meal-planner
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.0
  - name: postgresql
    version: 11.9.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://docs.tandoor.dev/
  - https://github.com/TandoorRecipes/recipes
  - https://hub.docker.com/r/vabene1111/recipes
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Bump appVersion to v1.4.4
