apiVersion: v2
name: pictshare
description: PictShare is an open source image, mp4, pastebin hosting service with a simple resizing and upload API that you can host yourself.
type: application
version: 0.1.1
appVersion: latest
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.0
sources:
  - https://github.com/HaschekSolutions/pictshare
