#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/hascheksolutions/pictshare
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 74ccf9f6

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- environment variables. [[ref]](https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/CONFIG.md)
# @default -- See [values.yaml](./values.yaml).
env: {}

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: false
    mountPath: /var/www/data
    retain: true
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi

podSecurityContext:
  # -- Volume group permissions
  fsGroup: 100
