apiVersion: v2
name: obico
description: Obico is a community-built, open-source smart 3D printing platform used by makers, enthusiasts, and tinkerers around the world.
home: https://charts.gabe565.com/charts/obico
icon: https://raw.githubusercontent.com/TheSpaghettiDetective/OctoPrint-Obico/master/octoprint_obico/static/img/logo-square.svg
type: application
version: 0.0.1
# renovate datasource=docker depName=ghcr.io/gabe565/obico/web
appVersion: sha-72b26dfa6f35800388816c621870664e5501dd19
kubeVersion: ">=1.22.0-0"
keywords:
  - 3d-printing
  - machine-learning
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.8.0
    condition: redis.enabled
sources:
  - https://github.com/gabe565/charts/tree/main/charts/obico
  - https://github.com/TheSpaghettiDetective/obico-server
  - https://github.com/gabe565/docker-obico
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Initial release
