apiVersion: v2
name: portfolio
description: My personal portfolio website
type: application
version: 0.1.1
appVersion: latest
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
  - name: postgresql
    version: 11.6.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/gabe565/portfolio
