apiVersion: v2
name: portfolio
description: My personal portfolio website
icon: https://raw.githubusercontent.com/gabe565/portfolio/0f0e80ce2f29e9382a64e7fc6fe2ed1a9993971b/public/android-chrome-512x512.png
type: application
version: 0.1.3
appVersion: latest
kubeVersion: ">=1.16.0-0"
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
  - name: postgresql
    version: 11.6.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/gabe565/portfolio
