#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/gabe565/portfolio
  # -- image pull policy
  pullPolicy: Always
  # -- image tag
  tag: latest

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- environment variables.
# @default -- See below
env:
  # APP_KEY: ""
  # APP_URL: ""
  DB_HOST: portfolio-postgresql
  DB_PORT: "5432"
  DB_DATABASE: portfolio
  DB_USERNAME: portfolio
  DB_PASSWORD:
    secretKeyRef:
      name: portfolio-postgresql
      key: postgres-password
  # MAIL_HOST: ""
  # MAIL_PORT: ""
  # MAIL_USERNAME: ""
  # MAIL_PASSWORD: ""
  # CONTACTFORM_TO_EMAIL: ""
  # CONTACTFORM_TO_NAME: ""
  # CONTACTFORM_FROM_EMAIL: ""

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: false
  auth:
    username: portfolio
    password: portfolio-pass
    database: portfolio
  primary:
    persistence:
      enabled: false
