#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/gabe565/portfolio
  # -- image pull policy
  pullPolicy: Always
  # -- image tag
  tag: latest

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- environment variables.
# @default -- See [values.yaml](./values.yaml)
env: {}
  # APP_KEY: ""
  # DB_HOST: postgresql
  # DB_PORT: "5432"
  # DB_DATABASE: portfolio
  # DB_USERNAME: portfolio
  # DB_PASSWORD:
  #   secretKeyRef:
  #     name: postgresql
  #     key: postgres-password
  # MAIL_HOST: ""
  # MAIL_PORT: ""
  # MAIL_USERNAME: ""
  # MAIL_PASSWORD: ""
  # CONTACTFORM_TO_EMAIL: ""
  # CONTACTFORM_TO_NAME: ""
  # CONTACTFORM_FROM_EMAIL: ""

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See [values.yaml](./values.yaml)
postgresql:
  enabled: false
  auth:
    database: portfolio
    postgresPassword: changeme
    # Uncomment to create a non-root user
    # username: portfolio
    # password: changeme
  primary:
    persistence:
      enabled: false
