{{/* Append the hardcoded settings */}}
{{- define "borgmatic.harcodedValues" -}}
env:
  {{- with .Values.ingress.main }}
  {{- if .enabled }}
  APP_URL: http{{ if ne ( len .tls ) 0 }}s{{ end }}://{{ (first .hosts).host }}
  {{- end }}
  {{- end }}

  {{- with .Values.postgresql }}
  {{- if .enabled }}
  DB_CONNECTION: pgsql
  DB_HOST: {{ $.Release.Name }}-postgresql
  DB_PORT: "5432"
  DB_DATABASE: {{ .auth.database }}
  DB_USERNAME: {{ .auth.username }}
  DB_PASSWORD:
    secretKeyRef:
      name: {{ $.Release.Name }}-postgresql
      key: password
  {{- end }}
  {{- end }}
{{- end -}}
{{- $_ := merge .Values (include "borgmatic.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
