apiVersion: v2
name: changedetection-io
description: Live your data-life pro-actively, track website content changes and receive notifications via Discord, Email, Slack, Telegram and 70+ more.
home: https://github.com/gabe565/charts/tree/main/charts/changedetection-io
icon: https://raw.githubusercontent.com/gabe565/charts/main/charts/changedetection-io/icon.png
type: application
version: 0.2.2
appVersion: 0.40.0.4
kubeVersion: ">=1.16.0-0"
keywords:
  - changedetection.io
  - change-detection
  - website-monitoring
  - website-change-tracker
sources:
  - https://github.com/dgtlmoon/changedetection.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Bump appVersion to v0.40.0.4
