apiVersion: v2
name: monica
description: Personal CRM. Remember everything about your friends, family and business relationships.
home: https://github.com/gabe565/charts/tree/main/charts/monica
icon: https://raw.githubusercontent.com/monicahq/monica/main/public/img/monica.svg
type: application
version: 0.1.0
appVersion: 3.7.0-fpm-alpine
kubeVersion: ">=1.16.0-0"
keywords:
  - crm
sources:
  - https://github.com/monicahq/monica
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.0
  - name: mariadb
    version: 11.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Initial release
