apiVersion: v2
name: limo
description: A file upload server.
home: https://github.com/gabe565/charts/tree/main/charts/limo
type: application
version: 0.1.17
appVersion: latest
kubeVersion: ">=1.16.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.0
  - name: postgresql
    version: 11.6.20
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/gabe565/limo
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add home URL
