#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/gabe565/limo
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: latest

controller:
  # -- Set the controller upgrade strategy
  strategy: RollingUpdate

# -- environment variables.
# @default -- See values.yaml
env:
  LIMOD_DB_HOST: "{{ .Release.Name }}-postgresql"
  LIMOD_DB_USERNAME: limo
  LIMOD_DB_PASSWORD: limo
  LIMOD_DB_DATABASE: limo

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  data:
    enabled: false

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: false
  auth:
    username: limo
    password: limo
    database: limo
  persistence:
    enabled: false
