{{/* Append the hardcoded settings */}}
{{- define "limo.harcodedValues" -}}
env:
  {{- with .Values.postgresql }}
  {{- if .enabled }}
  LIMOD_DB_HOST: {{ $.Release.Name }}-postgresql
  LIMOD_DB_PORT: "5432"
  LIMOD_DB_DATABASE: {{ .auth.database }}
  LIMOD_DB_USERNAME: {{ default "postgres" .auth.username }}
  LIMOD_DB_PASSWORD:
    secretKeyRef:
      name: {{ $.Release.Name }}-postgresql
      key: {{ if not .auth.password }}postgres-{{ end }}password
  {{- end }}
  {{- end }}
{{- end -}}
{{- $_ := merge .Values (include "limo.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
