#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s-labs/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

global:
  # To override bitnami images
  security:
    allowInsecureImages: true

image:
  # -- image repository
  repository: ghcr.io/usememos/memos
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 0.24.0

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    ports:
      http:
        port: 5230

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local
    #     hosts:
    #       - chart-example.local
    # @ignored

# -- Configure persistence settings for the chart under this key.
# @default -- See [values.yaml](./values.yaml)
persistence:
  data:
    enabled: false
    mountPath: /var/opt/memos
    retain: true
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi

podSecurityContext:
  # -- Run as `nobody` user
  runAsUser: 65534
  # -- Run as `nobody` group
  runAsGroup: 65534
  # -- Volume binds will be granted to `nobody` group
  fsGroup: 65534

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/main/bitnami/postgresql)
# @default -- See [values.yaml](./values.yaml)
postgresql:
  enabled: false
  image:
    registry: docker.io
    repository: library/postgres
    tag: "16-bookworm"
  auth:
    database: memos
    postgresPassword: changeme
  primary:
    args:
      - -c
      - config_file=/bitnami/postgresql/conf/postgresql.conf
      - -c
      - hba_file=/bitnami/postgresql/conf/pg_hba.conf
    configuration: |
      listen_addresses = '*'
      port = '5432'
      wal_level = 'replica'
      fsync = 'on'
      hot_standby = 'on'
      log_connections = 'false'
      log_disconnections = 'false'
      log_hostname = 'false'
      client_min_messages = 'error'
      include_dir = 'conf.d'
    pgHbaConfiguration: |
      host     all             all             0.0.0.0/0               scram-sha-256
      host     all             all             ::/0                    scram-sha-256
      local    all             all                                     scram-sha-256
      host     all             all        127.0.0.1/32                 scram-sha-256
      host     all             all        ::1/128                      scram-sha-256
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi

# -- Enable and configure mariadb database subchart under this key.
#    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/main/bitnami/mariadb)
# @default -- See [values.yaml](./values.yaml)
mariadb:
  enabled: false
  auth:
    database: memos
    username: memos
    password: changeme
    rootPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi
