apiVersion: v2
name: headscale
description: An open source, self-hosted implementation of the Tailscale control server.
home: https://github.com/gabe565/charts/tree/main/charts/headscale
icon: https://raw.githubusercontent.com/juanfont/headscale/641c6fd439a915150db3c2e83928e289b7e0c9d2/docs/logo/headscale3-dots.png
type: application
version: 0.1.15
appVersion: 0.16.4-alpine
kubeVersion: ">=1.16.0-0"
keywords:
  - headscale
  - tailscale
  - wireguard
  - vpn
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.0
  - name: postgresql
    version: 11.9.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/juanfont/headscale
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Remove config file and add docs for env config
    - kind: changed
      description: Generate `HEADSCALE_METRICS_LISTEN_ADDR` env from port in values
    - kind: fixed
      description: Set `HEADSCALE_LISTEN_ADDR` env and generate from port in values
