{{/* Append the hardcoded settings */}}
{{- define "nightscout.harcodedValues" -}}
env:
  HOSTNAME: "::"
  PORT: {{ .Values.service.main.ports.http.port | quote }}

  {{- with .Values.mongodb }}
  {{- if .enabled }}
  MONGODB_PASSWORD:
    secretKeyRef:
      name: {{ $.Release.Name }}-mongodb
      key: mongodb-passwords
  MONGODB_URI: mongodb://{{ first .auth.usernames }}:$(MONGODB_PASSWORD)@{{ $.Release.Name }}-mongodb/{{ first .auth.databases }}
  {{- end }}
  {{- end }}

termination:
  gracePeriodSeconds: "0"

configMaps:
  health:
    enabled: true
    data:
      ping_liveness.sh: |
        #!/bin/sh

        response="$(
          wget -q -O - \
            --header 'X-Forwarded-Proto: https' \
            "http://localhost:$PORT/api/v2/status" \
        )"
        if ! echo "$response" | grep -Fq 'STATUS OK'; then
          echo "$response"
          exit 1
        fi

persistence:
  health:
    enabled: true
    type: configMap
    name: "{{ include "bjw-s.common.lib.chart.names.fullname" . }}-health"
    mountPath: /health
    defaultMode: 0755

probes:
  liveness:
    custom: true
    spec:
      exec:
        command: [/health/ping_liveness.sh]
      periodSeconds: 30
{{- end -}}
{{- $_ := merge .Values (include "nightscout.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
