{{/* Append the hardcoded settings */}}
{{- define "nightscout.harcodedValues" -}}
env:
  HOSTNAME: "::"

  {{- with .Values.mongodb }}
  {{- if .enabled }}
  MONGODB_PASSWORD:
    secretKeyRef:
      name: {{ $.Release.Name }}-mongodb
      key: mongodb-passwords
  MONGODB_URI: mongodb://{{ first .auth.usernames }}:$(MONGODB_PASSWORD)@{{ $.Release.Name }}-mongodb/{{ first .auth.databases }}
  {{- end }}
  {{- end }}

termination:
  gracePeriodSeconds: "0"
{{- end -}}
{{- $_ := merge .Values (include "nightscout.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
