#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: akhilrex/hammond
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 1.0.0

# -- environment variables. [[ref]](https://github.com/akhilrex/hammond#environment-variables)
# @default -- See values.yaml
env: {}
  # JWT_SECRET: 20

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
  assets:
    enabled: false
