apiVersion: v2
name: relax-sounds
description: Relax Sounds is a website that lets you stream relaxing sounds to your browser or over Google Cast.
type: application
version: 0.1.0
appVersion: latest
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
sources:
  - https://github.com/gabe565/relax-sounds
