#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/gabe565/relax-sounds
          # -- image pull policy
          pullPolicy: Always
          # -- image tag
          tag: latest

        # -- environment variables.
        # @default -- See [values.yaml](./values.yaml)
        env: {}

        # -- Container security context.
        securityContext:
          readOnlyRootFilesystem: true

    pod:
      # -- Pod security context.
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    ports:
      http:
        port: 80
      metrics:
        port: 9090

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         service:
    #           name: main
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: false
    mountPath: /data
    retain: true
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi

serviceMonitor:
  main:
    # -- Enables or disables the serviceMonitor.
    enabled: false
    # -- Configures the endpoints for the serviceMonitor.
    # @default -- See [values.yaml](./values.yaml)
    endpoints:
      - port: metrics
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
