apiVersion: v2
name: podgrab
description: A self-hosted podcast manager to download episodes as soon as they become live.
type: application
version: 0.1.4
appVersion: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - podgrab
  - podcast
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.0
sources:
  - https://github.com/akhilrex/podgrab
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add keywords
