apiVersion: v2
name: podgrab
description: A self-hosted podcast manager to download episodes as soon as they become live.
type: application
version: 0.1.0
appVersion: latest
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.0
sources:
  - https://github.com/akhilrex/podgrab
