name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release-charts:
    name: Release Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add bitnami charts
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Add bjw-s charts
        run: |
          helm repo add bjw-s https://bjw-s.github.io/helm-charts

      - name: Remove readme images
        run: |
          set -x
          for f in charts/**/README.md; do
            sed -i '/^<img .* alt=".* logo"/,+1d' "$f"
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"

  deploy-markdown:
    name: Deploy Markdown
    needs: [release-charts]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish markdown
        run: |-
          rsync -av \
            --prune-empty-dirs \
            --include='*/' \
            --include='*.md' \
            --include=.gitignore \
            --exclude='*' \
            . docs

      - name: Replace yaml paths
        run: |
          set -x
          shopt -s globstar

          cd docs
          for f in **/*.md; do
            # Remove homepage line
            sed -i '/^\*\*Homepage:\*\*/,+1d' "$f"
            # Fix relative yaml links
            sed -i "s|(\./\(.*\.yaml\))|(${{ github.server_url }}/${{ github.repository }}/blob/main/$(dirname "$f")/\1)|g" "$f"
          done

      - name: Add charts to sidebar
        run: |
          export CHARTS="$(find charts -name README.md -exec sh -c 'basename "$(dirname "{}")"' \; | sort -h)"
          yq -i \
            '(.docs[] | select(.title == "Charts") | .children) = [(strenv(CHARTS) | split("\n") | .[] | {"title": ., "url": "/charts/" + . + "/"})]' \
            docs/_data/navigation.yml

      - name: Deploy markdown
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          clean-exclude: |
            artifacthub-repo.yml
            index.yaml
